<a href="https://colab.research.google.com/github/ayesha0859/DL/blob/main/DL_1AND_OR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def water_needed_and(soil_low, temp_high):
    w1 = 1
    w2 = 1
    theta = 2

    net_input = (w1 * soil_low) + (w2 * temp_high)

    return 1 if net_input >= theta else 0


print("| SoilLow | TempHigh => WaterNeeded")
for x1 in [0, 1]:
    for x2 in [0, 1]:
        print(f"|   {x1}     |    {x2}     =>       {water_needed_and(x1, x2)}")

| SoilLow | TempHigh => WaterNeeded
|   0     |    0     =>       0
|   0     |    1     =>       0
|   1     |    0     =>       0
|   1     |    1     =>       1


In [ ]:
def water_needed_or(soil_low, temp_high):
    w1 = 1
    w2 = 1
    theta = 1

    net_input = (w1 * soil_low) + (w2 * temp_high)

    return 1 if net_input >= theta else 0


print("\n| SoilLow | TempHigh => WaterNeeded")
for x1 in [0, 1]:
    for x2 in [0, 1]:
        print(f"|   {x1}     |    {x2}     =>       {water_needed_or(x1, x2)}")


| SoilLow | TempHigh => WaterNeeded
|   0     |    0     =>       0
|   0     |    1     =>       1
|   1     |    0     =>       1
|   1     |    1     =>       1


**Perceptron**

In [ ]:
import numpy as np

In [ ]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

In [ ]:
y = np.array([0, 1, 1, 1])

In [ ]:
weights = np.array([0.0, 0.0])
bias = 0.0
learning_rate = 0.1

In [ ]:
for epoch in range(10):
    for i in range(len(X)):
        # Calculate output
        net = np.dot(X[i], weights) + bias
        prediction = 1 if net >= 0 else 0

        # Update rule
        error = y[i] - prediction
        weights = weights + learning_rate * error * X[i]
        bias = bias + learning_rate * error

In [ ]:
print("SoilLow TempHigh => WaterNeeded")
for i in range(len(X)):
    net = np.dot(X[i], weights) + bias
    output = 1 if net >= 0 else 0
    print(X[i], "=>", output)

SoilLow TempHigh => WaterNeeded
[0 0] => 0
[0 1] => 1
[1 0] => 1
[1 1] => 1


detailed

In [ ]:
import numpy as np

In [ ]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([0, 0, 0, 1])

weights = np.array([0.0, 0.0])
bias = 0.0
learning_rate = 0.1
epochs = 5

In [ ]:
print("Initial Weights:", weights)
print("Initial Bias:", bias)
print("-" * 60)

#training
for epoch in range(epochs):
    print(f"\nEpoch {epoch + 1}")
    print("-" * 60)

    for i in range(len(X)):

        net = np.dot(X[i], weights) + bias

        #activation
        prediction = 1 if net >= 0 else 0

        #error
        error = y[i] - prediction

        #update weights and bias
        weights = weights + learning_rate * error * X[i]
        bias = bias + learning_rate * error

        print(f"Input: {X[i]}")
        print(f"Target Output: {y[i]}")
        print(f"Net Input: {net:.2f}")
        print(f"Predicted Output: {prediction}")
        print(f"Error: {error}")
        print(f"Updated Weights: {weights}")
        print(f"Updated Bias: {bias}")
        print("-" * 60)

print("\nFinal Weights:", weights)
print("Final Bias:", bias)

Initial Weights: [0. 0.]
Initial Bias: 0.0
------------------------------------------------------------

Epoch 1
------------------------------------------------------------
Input: [0 0]
Target Output: 0
Net Input: 0.00
Predicted Output: 1
Error: -1
Updated Weights: [0. 0.]
Updated Bias: -0.1
------------------------------------------------------------
Input: [0 1]
Target Output: 0
Net Input: -0.10
Predicted Output: 0
Error: 0
Updated Weights: [0. 0.]
Updated Bias: -0.1
------------------------------------------------------------
Input: [1 0]
Target Output: 0
Net Input: -0.10
Predicted Output: 0
Error: 0
Updated Weights: [0. 0.]
Updated Bias: -0.1
------------------------------------------------------------
Input: [1 1]
Target Output: 1
Net Input: -0.10
Predicted Output: 0
Error: 1
Updated Weights: [0.1 0.1]
Updated Bias: 0.0
------------------------------------------------------------

Epoch 2
------------------------------------------------------------
Input: [0 0]
Target Output: 0
N

**Back Propagation** XOR

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    return output * (1 - output)

In [ ]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([[0], [1], [1], [0]])

In [ ]:
np.random.seed(1)

W1 = np.random.rand(2, 2)   # input → hidden
b1 = np.zeros((1, 2))

W2 = np.random.rand(2, 1)   # hidden → output
b2 = np.zeros((1, 1))

learning_rate = 0.5
epochs = 5000

In [ ]:
for epoch in range(epochs):

    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    final_output = sigmoid(final_input)

    error = y - final_output
    mean_error = np.mean(np.abs(error))


    if mean_error < 0.01:
        print(f"Training stopped at epoch {epoch}")
        break


    d_output = error * sigmoid_derivative(final_output)
    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)


    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

In [ ]:
print("\nFinal Output after Training:")
for i in range(len(X)):
    print(X[i], "=>", round(final_output[i][0]))

print("\nBest Weights (Input → Hidden):\n", W1)
print("Best Weights (Hidden → Output):\n", W2)
print("Final Biases:\n", b1, b2)


Final Output after Training:
[0 0] => 0
[0 1] => 1
[1 0] => 1
[1 1] => 0

Best Weights (Input → Hidden):
 [[4.27469139 6.21243308]
 [4.26946779 6.19007008]]
Best Weights (Hidden → Output):
 [[-9.43976746]
 [ 8.74746572]]
Final Biases:
 [[-6.55739279 -2.70934281]] [[-4.00785419]]


detailed

In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    return output * (1 - output)

In [ ]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([[0], [1], [1], [0]])

In [ ]:
np.random.seed(1)

W1 = np.random.rand(2, 2)
b1 = np.zeros((1, 2))

W2 = np.random.rand(2, 1)
b2 = np.zeros((1, 1))

learning_rate = 0.5
epochs = 10

In [ ]:
for epoch in range(epochs):


    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    final_output = sigmoid(final_input)


    error = y - final_output
    mean_error = np.mean(np.abs(error))


    print(f"\nEpoch {epoch + 1}")
    print("Mean Error:", round(mean_error, 4))
    print("W1 (Input → Hidden):\n", np.round(W1, 2))
    print("b1:", np.round(b1, 4))
    print("W2 (Hidden → Output):\n", np.round(W2, 2))
    print("b2:", np.round(b2, 4))


    d_output = error * sigmoid_derivative(final_output)
    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)


    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate


Streaming output truncated to the last 5000 lines.
 [4.56 6.44]]
b1: [[-7.0077 -2.8624]]
W2 (Hidden → Output):
 [[-10.22]
 [  9.52]]
b2: [[-4.3999]]

Epoch 4547
Mean Error: 0.0181
W1 (Input → Hidden):
 [[4.57 6.46]
 [4.56 6.44]]
b1: [[-7.0078 -2.8624]]
W2 (Hidden → Output):
 [[-10.22]
 [  9.52]]
b2: [[-4.4]]

Epoch 4548
Mean Error: 0.0181
W1 (Input → Hidden):
 [[4.57 6.46]
 [4.56 6.44]]
b1: [[-7.0079 -2.8624]]
W2 (Hidden → Output):
 [[-10.22]
 [  9.52]]
b2: [[-4.4001]]

Epoch 4549
Mean Error: 0.0181
W1 (Input → Hidden):
 [[4.57 6.46]
 [4.56 6.44]]
b1: [[-7.0079 -2.8624]]
W2 (Hidden → Output):
 [[-10.22]
 [  9.52]]
b2: [[-4.4001]]

Epoch 4550
Mean Error: 0.0181
W1 (Input → Hidden):
 [[4.57 6.46]
 [4.56 6.44]]
b1: [[-7.008  -2.8625]]
W2 (Hidden → Output):
 [[-10.22]
 [  9.52]]
b2: [[-4.4002]]

Epoch 4551
Mean Error: 0.0181
W1 (Input → Hidden):
 [[4.57 6.46]
 [4.56 6.44]]
b1: [[-7.0081 -2.8625]]
W2 (Hidden → Output):
 [[-10.22]
 [  9.52]]
b2: [[-4.4002]]

Epoch 4552
Mean Error: 0.0181
W1 

**X**-**NOR**

In [ ]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    return output * (1 - output)

X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([[1], [0], [0], [1]])

np.random.seed(1)

W1 = np.random.rand(2, 2)
b1 = np.zeros((1, 2))

W2 = np.random.rand(2, 1)
b2 = np.zeros((1, 1))

learning_rate = 0.5
epochs = 5000

for epoch in range(epochs):

    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    final_output = sigmoid(final_input)

    error = y - final_output
    mean_error = np.mean(np.abs(error))


    if mean_error < 0.01:
        print(f"Training stopped at epoch {epoch}")
        break


    d_output = error * sigmoid_derivative(final_output)
    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)


    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    print("\nFinal Output after Training:")
    for i in range(len(X)):
      print(X[i], "=>", round(final_output[i][0]))

    print("\nBest Weights (Input → Hidden):\n", W1)
    print("Best Weights (Hidden → Output):\n", W2)
    print("Final Biases:\n", b1, b2)

Streaming output truncated to the last 5000 lines.
Best Weights (Hidden → Output):
 [[ 9.33078259]
 [-8.62957617]]
Final Biases:
 [[-6.46869924 -2.68904541]] [[3.94401346]]

Final Output after Training:
[0 0] => 1
[0 1] => 0
[1 0] => 0
[1 1] => 1

Best Weights (Input → Hidden):
 [[4.2177276  6.18517957]
 [4.21024385 6.1526947 ]]
Best Weights (Hidden → Output):
 [[ 9.33108084]
 [-8.62986877]]
Final Biases:
 [[-6.46888209 -2.68910777]] [[3.94416201]]

Final Output after Training:
[0 0] => 1
[0 1] => 0
[1 0] => 0
[1 1] => 1

Best Weights (Input → Hidden):
 [[4.2178459  6.18527399]
 [4.21036276 6.15279245]]
Best Weights (Hidden → Output):
 [[ 9.331379  ]
 [-8.63016128]]
Final Biases:
 [[-6.46906488 -2.68917011]] [[3.94431052]]

Final Output after Training:
[0 0] => 1
[0 1] => 0
[1 0] => 0
[1 1] => 1

Best Weights (Input → Hidden):
 [[4.21796415 6.18536839]
 [4.21048162 6.15289018]]
Best Weights (Hidden → Output):
 [[ 9.33167706]
 [-8.63045371]]
Final Biases:
 [[-6.4692476  -2.68923242]] [[

In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(o):
    return o * (1 - o)

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

np.random.seed(1)
W1 = np.random.rand(2,2)
b1 = np.zeros((1,2))
W2 = np.random.rand(2,1)
b2 = np.zeros((1,1))

lr = 0.5
epochs = 10

for epoch in range(epochs):
    # forward pass
    h_in = np.dot(X, W1) + b1
    h_out = sigmoid(h_in)

    f_in = np.dot(h_out, W2) + b2
    f_out = sigmoid(f_in)

    # error
    error = y - f_out
    mean_error = np.mean(np.abs(error))


    print(f"\nEpoch {epoch+1}")
    print("Mean Error:", round(mean_error, 4))
    print("W1 (Input → Hidden):\n", np.round(W1, 3))
    print("b1 (Hidden Bias):", np.round(b1, 3))
    print("W2 (Hidden → Output):\n", np.round(W2, 3))
    print("b2 (Output Bias):", np.round(b2, 3))

    # backpropagation
    d_out = error * sigmoid_derivative(f_out)
    d_hidden = d_out.dot(W2.T) * sigmoid_derivative(h_out)

    # weight n bias updates
    W2 += h_out.T.dot(d_out) * lr
    b2 += np.sum(d_out, axis=0, keepdims=True) * lr
    W1 += X.T.dot(d_hidden) * lr
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * lr


Epoch 1
Mean Error: 0.4999
W1 (Input → Hidden):
 [[0.417 0.72 ]
 [0.    0.302]]
b1 (Hidden Bias): [[0. 0.]]
W2 (Hidden → Output):
 [[0.147]
 [0.092]]
b2 (Output Bias): [[0.]]

Epoch 2
Mean Error: 0.4999
W1 (Input → Hidden):
 [[ 0.417  0.72 ]
 [-0.     0.302]]
b1 (Hidden Bias): [[-0.001 -0.   ]]
W2 (Hidden → Output):
 [[0.137]
 [0.082]]
b2 (Output Bias): [[-0.017]]

Epoch 3
Mean Error: 0.4999
W1 (Input → Hidden):
 [[ 0.416  0.72 ]
 [-0.     0.303]]
b1 (Hidden Bias): [[-0.001 -0.   ]]
W2 (Hidden → Output):
 [[0.13 ]
 [0.074]]
b2 (Output Bias): [[-0.031]]

Epoch 4
Mean Error: 0.4999
W1 (Input → Hidden):
 [[ 0.416  0.72 ]
 [-0.     0.303]]
b1 (Hidden Bias): [[-0.001 -0.   ]]
W2 (Hidden → Output):
 [[0.124]
 [0.068]]
b2 (Output Bias): [[-0.042]]

Epoch 5
Mean Error: 0.5
W1 (Input → Hidden):
 [[ 0.416  0.72 ]
 [-0.     0.303]]
b1 (Hidden Bias): [[-0.002 -0.001]]
W2 (Hidden → Output):
 [[0.119]
 [0.064]]
b2 (Output Bias): [[-0.05]]

Epoch 6
Mean Error: 0.5
W1 (Input → Hidden):
 [[ 0.416  0.7